version: 2.1
orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.9.3
jobs:
  build:
    docker:
      - image: node:16.13.2
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
