version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  build:
    docker:
      - image: node:16.13.2
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - slack/notify:
          channel: github_notification
          mentions: "@here"
