version: 2.1

orbs:
  node: circle-ci/node@4.7

jobs:
  test:
    steps:
      - checkout:
      - node/install-packages:
        pkg-manager: yarn
      - run:
        name: Test
        command: yarn test
