version: 2.1
orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.9.3

commands:
  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  build:
    docker:
      - image: node:16.13.2
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - notify_slack_pass
