version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
    example-workflow:
      jobs:
        - node/test:
            override-ci-command: yarn install --frozen-lockfile 
            run-command: yarn test 
