version: 2.1
orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.4.4
jobs:
  build:
    docker:
      - image: node:16.13.2
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - slack/on-hold:
        channel: "github_notification"
